In [1]:
import torch
import torchvision.models as model
import torch.nn as nn
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import transforms, datasets
import os
import glob
from tqdm import tqdm
from PIL import Image
import random
from sklearn.model_selection import train_test_split
import numpy as np
import timm.models as tmodels
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [21]:
m = ['X']
frame = [5,10,15]
method = ['DFD','DF','F2F','FS','NS']
v=[10,30,50,100]

w,h=224,224

transform = transforms.Compose([
    transforms.Resize((w,h)),
    transforms.ToTensor()
])

# one 

In [28]:
testmodel=tmodels.xception(pretrained=False)
if model == 'R18':
    testmodel = tmodels.resnet18(pretrained=False)
num_ftrs = testmodel.fc.in_features
testmodel.fc = nn.Linear(num_ftrs,2)
testmodel.load_state_dict(torch.load(f'weights/X_DFD_50_5_L2_T/best.pth'))
testmodel.cuda()

test_path = f'/media/data2/rjsdn/DeepFakeDetection/test'
test_img = datasets.ImageFolder(test_path,transform=transform)

test_loader = DataLoader(test_img,batch_size=16,shuffle=False,num_workers=8)

test_loss=0
acc = 0
count=0
p,r=torch.tensor([]),torch.tensor([])
testmodel.eval()
with torch.no_grad():
    for x,y in tqdm(test_loader):
        count+=1
        x=x.cuda()
        y=y.cuda()
        output = testmodel(x)
        pred=output.argmax(dim=1)
        p=torch.cat([p,pred.to("cpu")])
        r=torch.cat([r,y.to("cpu")])
        acc += pred.eq(y.view_as(pred)).sum().item()
    acc /= len(test_img)
    print("ACC : %.5f"%(acc*100))

print('#'*20)

100%|██████████| 250/250 [00:07<00:00, 31.89it/s]

ACC : 75.37500
####################


# DFD/frame/video

In [22]:
ans = {
                'DFD':[],
                'DF':[],
                'F2F':[],
                'FS':[],
                'NS':[]
            }

In [23]:
for model in m:
    for i in v:
        for f in frame:
            
            for me in method:
                print(model,i,f,me)
                testmodel=tmodels.xception(pretrained=False)
                if model == 'R18':
                    testmodel = tmodels.resnet18(pretrained=False)
                num_ftrs = testmodel.fc.in_features
                testmodel.fc = nn.Linear(num_ftrs,2)
                testmodel.load_state_dict(torch.load(f'weights/{model}_{me}_{i}_{f}_L2_T/best.pth'))
                testmodel.cuda()

                for j in range(1,6):
                    test_path = f'/media/data2/rjsdn/zoom/dataset/test{j}'
                    test_img = datasets.ImageFolder(test_path,transform=transform)

                    test_loader = DataLoader(test_img,batch_size=16,shuffle=False,num_workers=8)

                    test_loss=0
                    acc = 0
                    count=0
                    p,r=torch.tensor([]),torch.tensor([])
                    testmodel.eval()
                    with torch.no_grad():
                        for x,y in tqdm(test_loader):
                            count+=1
                            x=x.cuda()
                            y=y.cuda()
                            output = testmodel(x)
                            pred=output.argmax(dim=1)
                            p=torch.cat([p,pred.to("cpu")])
                            r=torch.cat([r,y.to("cpu")])
                            acc += pred.eq(y.view_as(pred)).sum().item()
                        acc /= len(test_img)
                        print("ACC : %.5f"%(acc*100))
                    
                    ans[me].append(acc*100)
                ans[me].append(' ')

                print('#'*20)

X 10 5 DFD


100%|██████████| 250/250 [00:07<00:00, 31.85it/s]


ACC : 77.02500


100%|██████████| 250/250 [00:07<00:00, 31.36it/s]


ACC : 77.05000


100%|██████████| 250/250 [00:07<00:00, 31.65it/s]


ACC : 75.55000


100%|██████████| 250/250 [00:07<00:00, 32.25it/s]


ACC : 78.52500


100%|██████████| 250/250 [00:07<00:00, 31.80it/s]


ACC : 80.45000
####################
X 10 5 DF


100%|██████████| 250/250 [00:07<00:00, 31.88it/s]


ACC : 89.25000


100%|██████████| 250/250 [00:07<00:00, 31.74it/s]


ACC : 87.70000


100%|██████████| 250/250 [00:07<00:00, 31.44it/s]


ACC : 86.15000


100%|██████████| 250/250 [00:07<00:00, 31.51it/s]


ACC : 90.37500


100%|██████████| 250/250 [00:07<00:00, 31.51it/s]


ACC : 87.57500
####################
X 10 5 F2F


100%|██████████| 250/250 [00:07<00:00, 31.70it/s]


ACC : 84.27500


100%|██████████| 250/250 [00:07<00:00, 31.56it/s]


ACC : 79.95000


100%|██████████| 250/250 [00:07<00:00, 31.58it/s]


ACC : 71.30000


100%|██████████| 250/250 [00:07<00:00, 31.70it/s]


ACC : 75.42500


100%|██████████| 250/250 [00:07<00:00, 31.62it/s]


ACC : 87.62500
####################
X 10 5 FS


100%|██████████| 250/250 [00:07<00:00, 31.43it/s]


ACC : 79.22500


100%|██████████| 250/250 [00:08<00:00, 31.19it/s]


ACC : 73.92500


100%|██████████| 250/250 [00:07<00:00, 31.26it/s]


ACC : 68.52500


100%|██████████| 250/250 [00:07<00:00, 31.56it/s]


ACC : 75.40000


100%|██████████| 250/250 [00:08<00:00, 31.15it/s]


ACC : 82.10000
####################
X 10 5 NS


100%|██████████| 250/250 [00:07<00:00, 31.54it/s]


ACC : 93.42500


100%|██████████| 250/250 [00:07<00:00, 31.54it/s]


ACC : 93.67500


100%|██████████| 250/250 [00:07<00:00, 31.53it/s]


ACC : 87.40000


100%|██████████| 250/250 [00:07<00:00, 31.27it/s]


ACC : 88.52500


100%|██████████| 250/250 [00:07<00:00, 31.32it/s]


ACC : 93.90000
####################
X 10 10 DFD


100%|██████████| 250/250 [00:07<00:00, 31.40it/s]


ACC : 78.87500


100%|██████████| 250/250 [00:08<00:00, 31.25it/s]


ACC : 78.00000


100%|██████████| 250/250 [00:08<00:00, 30.97it/s]


ACC : 77.17500


100%|██████████| 250/250 [00:08<00:00, 30.88it/s]


ACC : 79.22500


100%|██████████| 250/250 [00:07<00:00, 31.25it/s]


ACC : 82.90000
####################
X 10 10 DF


100%|██████████| 250/250 [00:07<00:00, 31.68it/s]


ACC : 86.12500


100%|██████████| 250/250 [00:08<00:00, 30.93it/s]


ACC : 86.40000


100%|██████████| 250/250 [00:07<00:00, 31.59it/s]


ACC : 84.20000


100%|██████████| 250/250 [00:08<00:00, 31.04it/s]


ACC : 90.07500


100%|██████████| 250/250 [00:08<00:00, 31.00it/s]


ACC : 86.47500
####################
X 10 10 F2F


100%|██████████| 250/250 [00:07<00:00, 31.28it/s]


ACC : 84.12500


100%|██████████| 250/250 [00:08<00:00, 31.11it/s]


ACC : 78.95000


100%|██████████| 250/250 [00:08<00:00, 30.67it/s]


ACC : 69.95000


100%|██████████| 250/250 [00:08<00:00, 31.19it/s]


ACC : 74.20000


100%|██████████| 250/250 [00:08<00:00, 31.25it/s]


ACC : 86.90000
####################
X 10 10 FS


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 84.67500


100%|██████████| 250/250 [00:07<00:00, 31.29it/s]


ACC : 80.67500


100%|██████████| 250/250 [00:07<00:00, 31.45it/s]


ACC : 74.97500


100%|██████████| 250/250 [00:07<00:00, 31.36it/s]


ACC : 80.42500


100%|██████████| 250/250 [00:08<00:00, 31.03it/s]


ACC : 85.65000
####################
X 10 10 NS


100%|██████████| 250/250 [00:08<00:00, 31.24it/s]


ACC : 95.22500


100%|██████████| 250/250 [00:08<00:00, 31.15it/s]


ACC : 95.02500


100%|██████████| 250/250 [00:08<00:00, 31.21it/s]


ACC : 90.45000


100%|██████████| 250/250 [00:08<00:00, 31.19it/s]


ACC : 89.87500


100%|██████████| 250/250 [00:08<00:00, 31.02it/s]


ACC : 95.10000
####################
X 10 15 DFD


100%|██████████| 250/250 [00:08<00:00, 30.99it/s]


ACC : 80.30000


100%|██████████| 250/250 [00:08<00:00, 31.15it/s]


ACC : 77.90000


100%|██████████| 250/250 [00:08<00:00, 30.89it/s]


ACC : 78.72500


100%|██████████| 250/250 [00:08<00:00, 30.84it/s]


ACC : 80.32500


100%|██████████| 250/250 [00:08<00:00, 31.04it/s]


ACC : 82.47500
####################
X 10 15 DF


100%|██████████| 250/250 [00:08<00:00, 30.96it/s]


ACC : 88.52500


100%|██████████| 250/250 [00:08<00:00, 31.24it/s]


ACC : 88.95000


100%|██████████| 250/250 [00:08<00:00, 30.88it/s]


ACC : 86.02500


100%|██████████| 250/250 [00:08<00:00, 31.02it/s]


ACC : 91.42500


100%|██████████| 250/250 [00:08<00:00, 30.74it/s]


ACC : 88.72500
####################
X 10 15 F2F


100%|██████████| 250/250 [00:07<00:00, 31.27it/s]


ACC : 83.62500


100%|██████████| 250/250 [00:08<00:00, 30.92it/s]


ACC : 78.62500


100%|██████████| 250/250 [00:08<00:00, 30.55it/s]


ACC : 69.97500


100%|██████████| 250/250 [00:08<00:00, 30.86it/s]


ACC : 73.65000


100%|██████████| 250/250 [00:08<00:00, 31.11it/s]


ACC : 86.67500
####################
X 10 15 FS


100%|██████████| 250/250 [00:08<00:00, 30.94it/s]


ACC : 84.60000


100%|██████████| 250/250 [00:08<00:00, 30.80it/s]


ACC : 80.25000


100%|██████████| 250/250 [00:08<00:00, 31.08it/s]


ACC : 74.40000


100%|██████████| 250/250 [00:08<00:00, 31.09it/s]


ACC : 81.10000


100%|██████████| 250/250 [00:08<00:00, 30.75it/s]


ACC : 85.62500
####################
X 10 15 NS


100%|██████████| 250/250 [00:08<00:00, 30.99it/s]


ACC : 94.52500


100%|██████████| 250/250 [00:08<00:00, 31.09it/s]


ACC : 94.57500


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 89.47500


100%|██████████| 250/250 [00:08<00:00, 30.82it/s]


ACC : 89.37500


100%|██████████| 250/250 [00:08<00:00, 31.15it/s]


ACC : 94.70000
####################
X 30 5 DFD


100%|██████████| 250/250 [00:08<00:00, 30.99it/s]


ACC : 81.97500


100%|██████████| 250/250 [00:08<00:00, 30.76it/s]


ACC : 83.10000


100%|██████████| 250/250 [00:08<00:00, 30.94it/s]


ACC : 81.67500


100%|██████████| 250/250 [00:08<00:00, 30.99it/s]


ACC : 83.77500


100%|██████████| 250/250 [00:08<00:00, 31.01it/s]


ACC : 83.80000
####################
X 30 5 DF


100%|██████████| 250/250 [00:08<00:00, 31.12it/s]


ACC : 93.95000


100%|██████████| 250/250 [00:08<00:00, 28.32it/s]


ACC : 94.30000


100%|██████████| 250/250 [00:08<00:00, 29.95it/s]


ACC : 91.57500


100%|██████████| 250/250 [00:08<00:00, 29.91it/s]


ACC : 94.62500


100%|██████████| 250/250 [00:08<00:00, 30.92it/s]


ACC : 92.47500
####################
X 30 5 F2F


100%|██████████| 250/250 [00:08<00:00, 31.10it/s]


ACC : 91.60000


100%|██████████| 250/250 [00:08<00:00, 30.91it/s]


ACC : 86.50000


100%|██████████| 250/250 [00:07<00:00, 31.45it/s]


ACC : 78.97500


100%|██████████| 250/250 [00:08<00:00, 30.95it/s]


ACC : 82.65000


100%|██████████| 250/250 [00:08<00:00, 31.23it/s]


ACC : 90.95000
####################
X 30 5 FS


100%|██████████| 250/250 [00:08<00:00, 31.11it/s]


ACC : 90.80000


100%|██████████| 250/250 [00:08<00:00, 31.13it/s]


ACC : 86.77500


100%|██████████| 250/250 [00:08<00:00, 30.83it/s]


ACC : 83.55000


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 86.72500


100%|██████████| 250/250 [00:08<00:00, 31.24it/s]


ACC : 90.27500
####################
X 30 5 NS


100%|██████████| 250/250 [00:07<00:00, 31.60it/s]


ACC : 98.75000


100%|██████████| 250/250 [00:08<00:00, 31.21it/s]


ACC : 99.12500


100%|██████████| 250/250 [00:08<00:00, 31.20it/s]


ACC : 96.00000


100%|██████████| 250/250 [00:08<00:00, 30.96it/s]


ACC : 96.00000


100%|██████████| 250/250 [00:08<00:00, 30.83it/s]


ACC : 97.35000
####################
X 30 10 DFD


100%|██████████| 250/250 [00:07<00:00, 31.27it/s]


ACC : 83.15000


100%|██████████| 250/250 [00:08<00:00, 31.12it/s]


ACC : 83.30000


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 81.55000


100%|██████████| 250/250 [00:08<00:00, 30.92it/s]


ACC : 84.82500


100%|██████████| 250/250 [00:08<00:00, 30.50it/s]


ACC : 85.25000
####################
X 30 10 DF


100%|██████████| 250/250 [00:08<00:00, 30.92it/s]


ACC : 96.12500


100%|██████████| 250/250 [00:08<00:00, 30.83it/s]


ACC : 96.85000


100%|██████████| 250/250 [00:08<00:00, 30.87it/s]


ACC : 94.42500


100%|██████████| 250/250 [00:08<00:00, 31.13it/s]


ACC : 96.92500


100%|██████████| 250/250 [00:08<00:00, 31.20it/s]


ACC : 96.47500
####################
X 30 10 F2F


100%|██████████| 250/250 [00:07<00:00, 31.26it/s]


ACC : 92.60000


100%|██████████| 250/250 [00:08<00:00, 31.20it/s]


ACC : 87.52500


100%|██████████| 250/250 [00:07<00:00, 31.70it/s]


ACC : 82.35000


100%|██████████| 250/250 [00:08<00:00, 31.25it/s]


ACC : 84.42500


100%|██████████| 250/250 [00:08<00:00, 31.21it/s]


ACC : 92.42500
####################
X 30 10 FS


100%|██████████| 250/250 [00:07<00:00, 31.36it/s]


ACC : 92.77500


100%|██████████| 250/250 [00:08<00:00, 31.00it/s]


ACC : 88.50000


100%|██████████| 250/250 [00:08<00:00, 31.22it/s]


ACC : 85.65000


100%|██████████| 250/250 [00:07<00:00, 31.41it/s]


ACC : 89.12500


100%|██████████| 250/250 [00:07<00:00, 31.43it/s]


ACC : 90.85000
####################
X 30 10 NS


100%|██████████| 250/250 [00:08<00:00, 31.25it/s]


ACC : 98.90000


100%|██████████| 250/250 [00:08<00:00, 31.02it/s]


ACC : 99.00000


100%|██████████| 250/250 [00:07<00:00, 31.44it/s]


ACC : 95.85000


100%|██████████| 250/250 [00:08<00:00, 30.99it/s]


ACC : 96.25000


100%|██████████| 250/250 [00:08<00:00, 30.93it/s]


ACC : 97.70000
####################
X 30 15 DFD


100%|██████████| 250/250 [00:08<00:00, 30.95it/s]


ACC : 84.27500


100%|██████████| 250/250 [00:08<00:00, 30.77it/s]


ACC : 83.80000


100%|██████████| 250/250 [00:08<00:00, 30.99it/s]


ACC : 83.25000


100%|██████████| 250/250 [00:08<00:00, 31.22it/s]


ACC : 85.72500


100%|██████████| 250/250 [00:07<00:00, 31.28it/s]


ACC : 86.05000
####################
X 30 15 DF


100%|██████████| 250/250 [00:07<00:00, 31.50it/s]


ACC : 96.07500


100%|██████████| 250/250 [00:08<00:00, 31.16it/s]


ACC : 97.35000


100%|██████████| 250/250 [00:08<00:00, 30.96it/s]


ACC : 95.42500


100%|██████████| 250/250 [00:07<00:00, 31.33it/s]


ACC : 97.50000


100%|██████████| 250/250 [00:07<00:00, 31.53it/s]


ACC : 95.72500
####################
X 30 15 F2F


100%|██████████| 250/250 [00:07<00:00, 31.78it/s]


ACC : 93.55000


100%|██████████| 250/250 [00:07<00:00, 31.27it/s]


ACC : 89.10000


100%|██████████| 250/250 [00:07<00:00, 31.50it/s]


ACC : 83.87500


100%|██████████| 250/250 [00:07<00:00, 31.48it/s]


ACC : 85.82500


100%|██████████| 250/250 [00:08<00:00, 31.23it/s]


ACC : 93.42500
####################
X 30 15 FS


100%|██████████| 250/250 [00:08<00:00, 31.20it/s]


ACC : 93.20000


100%|██████████| 250/250 [00:08<00:00, 31.16it/s]


ACC : 89.32500


100%|██████████| 250/250 [00:07<00:00, 31.43it/s]


ACC : 85.87500


100%|██████████| 250/250 [00:08<00:00, 31.22it/s]


ACC : 88.45000


100%|██████████| 250/250 [00:08<00:00, 31.05it/s]


ACC : 90.47500
####################
X 30 15 NS


100%|██████████| 250/250 [00:07<00:00, 31.69it/s]


ACC : 98.87500


100%|██████████| 250/250 [00:08<00:00, 30.97it/s]


ACC : 99.27500


100%|██████████| 250/250 [00:08<00:00, 30.95it/s]


ACC : 96.20000


100%|██████████| 250/250 [00:07<00:00, 31.36it/s]


ACC : 96.40000


100%|██████████| 250/250 [00:07<00:00, 31.48it/s]


ACC : 97.62500
####################
X 50 5 DFD


100%|██████████| 250/250 [00:07<00:00, 31.74it/s]


ACC : 89.82500


100%|██████████| 250/250 [00:08<00:00, 31.10it/s]


ACC : 87.52500


100%|██████████| 250/250 [00:07<00:00, 31.38it/s]


ACC : 89.82500


100%|██████████| 250/250 [00:08<00:00, 30.90it/s]


ACC : 91.30000


100%|██████████| 250/250 [00:07<00:00, 31.46it/s]


ACC : 88.85000
####################
X 50 5 DF


100%|██████████| 250/250 [00:07<00:00, 31.58it/s]


ACC : 95.22500


100%|██████████| 250/250 [00:07<00:00, 31.40it/s]


ACC : 96.60000


100%|██████████| 250/250 [00:07<00:00, 31.47it/s]


ACC : 93.05000


100%|██████████| 250/250 [00:08<00:00, 31.25it/s]


ACC : 96.95000


100%|██████████| 250/250 [00:08<00:00, 31.22it/s]


ACC : 95.60000
####################
X 50 5 F2F


100%|██████████| 250/250 [00:08<00:00, 31.10it/s]


ACC : 93.75000


100%|██████████| 250/250 [00:08<00:00, 31.20it/s]


ACC : 90.80000


100%|██████████| 250/250 [00:08<00:00, 31.13it/s]


ACC : 84.85000


100%|██████████| 250/250 [00:08<00:00, 31.16it/s]


ACC : 87.45000


100%|██████████| 250/250 [00:07<00:00, 31.31it/s]


ACC : 94.00000
####################
X 50 5 FS


100%|██████████| 250/250 [00:07<00:00, 31.32it/s]


ACC : 96.52500


100%|██████████| 250/250 [00:07<00:00, 31.28it/s]


ACC : 94.07500


100%|██████████| 250/250 [00:08<00:00, 31.16it/s]


ACC : 92.92500


100%|██████████| 250/250 [00:07<00:00, 31.58it/s]


ACC : 94.65000


100%|██████████| 250/250 [00:08<00:00, 31.24it/s]


ACC : 95.45000
####################
X 50 5 NS


100%|██████████| 250/250 [00:07<00:00, 31.47it/s]


ACC : 98.75000


100%|██████████| 250/250 [00:07<00:00, 31.26it/s]


ACC : 98.90000


100%|██████████| 250/250 [00:07<00:00, 31.26it/s]


ACC : 95.65000


100%|██████████| 250/250 [00:08<00:00, 31.23it/s]


ACC : 95.85000


100%|██████████| 250/250 [00:07<00:00, 31.49it/s]


ACC : 97.12500
####################
X 50 10 DFD


100%|██████████| 250/250 [00:07<00:00, 31.27it/s]


ACC : 90.52500


100%|██████████| 250/250 [00:07<00:00, 31.29it/s]


ACC : 89.92500


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 91.17500


100%|██████████| 250/250 [00:08<00:00, 31.21it/s]


ACC : 92.67500


100%|██████████| 250/250 [00:08<00:00, 31.14it/s]


ACC : 91.77500
####################
X 50 10 DF


100%|██████████| 250/250 [00:07<00:00, 31.44it/s]


ACC : 96.57500


100%|██████████| 250/250 [00:08<00:00, 31.00it/s]


ACC : 98.20000


100%|██████████| 250/250 [00:07<00:00, 31.32it/s]


ACC : 95.82500


100%|██████████| 250/250 [00:07<00:00, 31.55it/s]


ACC : 98.00000


100%|██████████| 250/250 [00:07<00:00, 31.25it/s]


ACC : 97.10000
####################
X 50 10 F2F


100%|██████████| 250/250 [00:07<00:00, 31.52it/s]


ACC : 94.20000


100%|██████████| 250/250 [00:07<00:00, 31.36it/s]


ACC : 91.82500


100%|██████████| 250/250 [00:07<00:00, 31.37it/s]


ACC : 85.90000


100%|██████████| 250/250 [00:08<00:00, 31.03it/s]


ACC : 89.00000


100%|██████████| 250/250 [00:07<00:00, 31.42it/s]


ACC : 94.65000
####################
X 50 10 FS


100%|██████████| 250/250 [00:07<00:00, 31.34it/s]


ACC : 97.25000


100%|██████████| 250/250 [00:08<00:00, 31.21it/s]


ACC : 95.10000


100%|██████████| 250/250 [00:07<00:00, 31.27it/s]


ACC : 93.72500


100%|██████████| 250/250 [00:08<00:00, 31.14it/s]


ACC : 95.10000


100%|██████████| 250/250 [00:08<00:00, 31.18it/s]


ACC : 96.25000
####################
X 50 10 NS


100%|██████████| 250/250 [00:07<00:00, 31.34it/s]


ACC : 98.95000


100%|██████████| 250/250 [00:07<00:00, 31.26it/s]


ACC : 99.12500


100%|██████████| 250/250 [00:07<00:00, 31.49it/s]


ACC : 95.95000


100%|██████████| 250/250 [00:07<00:00, 31.52it/s]


ACC : 96.35000


100%|██████████| 250/250 [00:08<00:00, 31.13it/s]


ACC : 97.62500
####################
X 50 15 DFD


100%|██████████| 250/250 [00:08<00:00, 30.99it/s]


ACC : 90.45000


100%|██████████| 250/250 [00:08<00:00, 31.15it/s]


ACC : 91.15000


100%|██████████| 250/250 [00:08<00:00, 30.96it/s]


ACC : 91.90000


100%|██████████| 250/250 [00:08<00:00, 30.92it/s]


ACC : 91.17500


100%|██████████| 250/250 [00:08<00:00, 31.08it/s]


ACC : 90.42500
####################
X 50 15 DF


100%|██████████| 250/250 [00:08<00:00, 31.20it/s]


ACC : 96.57500


100%|██████████| 250/250 [00:08<00:00, 31.14it/s]


ACC : 98.60000


100%|██████████| 250/250 [00:07<00:00, 31.51it/s]


ACC : 97.22500


100%|██████████| 250/250 [00:07<00:00, 31.47it/s]


ACC : 98.67500


100%|██████████| 250/250 [00:07<00:00, 31.44it/s]


ACC : 98.00000
####################
X 50 15 F2F


100%|██████████| 250/250 [00:07<00:00, 31.53it/s]


ACC : 95.35000


100%|██████████| 250/250 [00:07<00:00, 31.37it/s]


ACC : 92.72500


100%|██████████| 250/250 [00:07<00:00, 31.39it/s]


ACC : 87.85000


100%|██████████| 250/250 [00:07<00:00, 31.55it/s]


ACC : 90.10000


100%|██████████| 250/250 [00:08<00:00, 31.05it/s]


ACC : 95.87500
####################
X 50 15 FS


100%|██████████| 250/250 [00:07<00:00, 31.36it/s]


ACC : 96.95000


100%|██████████| 250/250 [00:07<00:00, 31.37it/s]


ACC : 94.82500


100%|██████████| 250/250 [00:07<00:00, 31.27it/s]


ACC : 93.30000


100%|██████████| 250/250 [00:07<00:00, 31.52it/s]


ACC : 95.22500


100%|██████████| 250/250 [00:07<00:00, 31.29it/s]


ACC : 96.72500
####################
X 50 15 NS


100%|██████████| 250/250 [00:07<00:00, 31.38it/s]


ACC : 99.17500


100%|██████████| 250/250 [00:07<00:00, 31.43it/s]


ACC : 99.32500


100%|██████████| 250/250 [00:07<00:00, 31.46it/s]


ACC : 96.30000


100%|██████████| 250/250 [00:07<00:00, 31.56it/s]


ACC : 96.72500


100%|██████████| 250/250 [00:07<00:00, 31.39it/s]


ACC : 98.22500
####################
X 100 5 DFD


100%|██████████| 250/250 [00:07<00:00, 31.29it/s]


ACC : 93.75000


100%|██████████| 250/250 [00:07<00:00, 31.31it/s]


ACC : 91.05000


100%|██████████| 250/250 [00:07<00:00, 31.26it/s]


ACC : 94.60000


100%|██████████| 250/250 [00:08<00:00, 31.13it/s]


ACC : 94.20000


100%|██████████| 250/250 [00:07<00:00, 31.47it/s]


ACC : 94.35000
####################
X 100 5 DF


100%|██████████| 250/250 [00:07<00:00, 31.52it/s]


ACC : 97.65000


100%|██████████| 250/250 [00:07<00:00, 31.30it/s]


ACC : 98.42500


100%|██████████| 250/250 [00:07<00:00, 31.31it/s]


ACC : 97.22500


100%|██████████| 250/250 [00:07<00:00, 31.28it/s]


ACC : 98.62500


100%|██████████| 250/250 [00:08<00:00, 31.25it/s]


ACC : 98.10000
####################
X 100 5 F2F


100%|██████████| 250/250 [00:08<00:00, 30.92it/s]


ACC : 94.92500


100%|██████████| 250/250 [00:08<00:00, 30.98it/s]


ACC : 95.17500


100%|██████████| 250/250 [00:07<00:00, 31.41it/s]


ACC : 90.02500


100%|██████████| 250/250 [00:07<00:00, 31.40it/s]


ACC : 92.45000


100%|██████████| 250/250 [00:08<00:00, 31.11it/s]


ACC : 96.22500
####################
X 100 5 FS


100%|██████████| 250/250 [00:07<00:00, 31.67it/s]


ACC : 98.10000


100%|██████████| 250/250 [00:08<00:00, 31.18it/s]


ACC : 96.45000


100%|██████████| 250/250 [00:07<00:00, 31.28it/s]


ACC : 96.00000


100%|██████████| 250/250 [00:07<00:00, 31.46it/s]


ACC : 96.97500


100%|██████████| 250/250 [00:07<00:00, 31.40it/s]


ACC : 96.85000
####################
X 100 5 NS


100%|██████████| 250/250 [00:07<00:00, 31.42it/s]


ACC : 99.30000


100%|██████████| 250/250 [00:08<00:00, 31.21it/s]


ACC : 99.37500


100%|██████████| 250/250 [00:07<00:00, 31.60it/s]


ACC : 97.45000


100%|██████████| 250/250 [00:07<00:00, 31.53it/s]


ACC : 97.32500


100%|██████████| 250/250 [00:08<00:00, 28.24it/s]


ACC : 98.60000
####################
X 100 10 DFD


100%|██████████| 250/250 [00:08<00:00, 31.15it/s]


ACC : 94.72500


100%|██████████| 250/250 [00:07<00:00, 31.33it/s]


ACC : 94.47500


100%|██████████| 250/250 [00:07<00:00, 31.61it/s]


ACC : 97.05000


100%|██████████| 250/250 [00:07<00:00, 31.27it/s]


ACC : 95.07500


100%|██████████| 250/250 [00:07<00:00, 31.56it/s]


ACC : 96.97500
####################
X 100 10 DF


100%|██████████| 250/250 [00:08<00:00, 31.17it/s]


ACC : 97.87500


100%|██████████| 250/250 [00:08<00:00, 31.10it/s]


ACC : 98.87500


100%|██████████| 250/250 [00:07<00:00, 31.64it/s]


ACC : 97.72500


100%|██████████| 250/250 [00:07<00:00, 31.57it/s]


ACC : 98.52500


100%|██████████| 250/250 [00:08<00:00, 31.22it/s]


ACC : 98.55000
####################
X 100 10 F2F


100%|██████████| 250/250 [00:07<00:00, 31.26it/s]


ACC : 96.05000


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 96.80000


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 92.52500


100%|██████████| 250/250 [00:08<00:00, 31.06it/s]


ACC : 94.40000


100%|██████████| 250/250 [00:07<00:00, 31.56it/s]


ACC : 97.32500
####################
X 100 10 FS


100%|██████████| 250/250 [00:07<00:00, 31.51it/s]


ACC : 99.12500


100%|██████████| 250/250 [00:07<00:00, 31.31it/s]


ACC : 97.37500


100%|██████████| 250/250 [00:08<00:00, 31.16it/s]


ACC : 97.97500


100%|██████████| 250/250 [00:07<00:00, 31.33it/s]


ACC : 98.17500


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 98.75000
####################
X 100 10 NS


100%|██████████| 250/250 [00:07<00:00, 31.70it/s]


ACC : 99.65000


100%|██████████| 250/250 [00:07<00:00, 31.58it/s]


ACC : 99.80000


100%|██████████| 250/250 [00:08<00:00, 31.19it/s]


ACC : 97.62500


100%|██████████| 250/250 [00:08<00:00, 31.12it/s]


ACC : 97.92500


100%|██████████| 250/250 [00:08<00:00, 31.04it/s]


ACC : 98.57500
####################
X 100 15 DFD


100%|██████████| 250/250 [00:07<00:00, 31.57it/s]


ACC : 95.75000


100%|██████████| 250/250 [00:07<00:00, 31.40it/s]


ACC : 95.47500


100%|██████████| 250/250 [00:08<00:00, 31.17it/s]


ACC : 98.12500


100%|██████████| 250/250 [00:08<00:00, 31.07it/s]


ACC : 97.37500


100%|██████████| 250/250 [00:08<00:00, 31.21it/s]


ACC : 98.40000
####################
X 100 15 DF


100%|██████████| 250/250 [00:07<00:00, 31.69it/s]


ACC : 98.40000


100%|██████████| 250/250 [00:07<00:00, 31.51it/s]


ACC : 99.00000


100%|██████████| 250/250 [00:07<00:00, 31.58it/s]


ACC : 98.65000


100%|██████████| 250/250 [00:08<00:00, 31.06it/s]


ACC : 98.90000


100%|██████████| 250/250 [00:07<00:00, 31.31it/s]


ACC : 98.87500
####################
X 100 15 F2F


100%|██████████| 250/250 [00:07<00:00, 31.32it/s]


ACC : 97.57500


100%|██████████| 250/250 [00:07<00:00, 31.36it/s]


ACC : 97.30000


100%|██████████| 250/250 [00:08<00:00, 30.79it/s]


ACC : 92.35000


100%|██████████| 250/250 [00:08<00:00, 31.10it/s]


ACC : 95.17500


100%|██████████| 250/250 [00:08<00:00, 31.12it/s]


ACC : 98.50000
####################
X 100 15 FS


100%|██████████| 250/250 [00:07<00:00, 31.37it/s]


ACC : 99.22500


100%|██████████| 250/250 [00:07<00:00, 31.37it/s]


ACC : 97.55000


100%|██████████| 250/250 [00:07<00:00, 31.32it/s]


ACC : 97.87500


100%|██████████| 250/250 [00:08<00:00, 31.20it/s]


ACC : 97.87500


100%|██████████| 250/250 [00:08<00:00, 31.06it/s]


ACC : 98.77500
####################
X 100 15 NS


100%|██████████| 250/250 [00:07<00:00, 31.62it/s]


ACC : 99.37500


100%|██████████| 250/250 [00:07<00:00, 31.57it/s]


ACC : 99.25000


100%|██████████| 250/250 [00:07<00:00, 31.28it/s]


ACC : 96.77500


100%|██████████| 250/250 [00:08<00:00, 31.09it/s]


ACC : 97.37500


100%|██████████| 250/250 [00:07<00:00, 31.37it/s]

ACC : 98.47500
####################


In [24]:
import pandas as pd

In [25]:
pd.DataFrame(ans).to_csv('./X_res.csv',index=False)

# DFD,FS, ...

In [3]:
for model in m:
    for i in k:
        print(model,i)
        testmodel=tmodels.xception(pretrained=False)
        if model == 'R18':
            testmodel = tmodels.resnet18(pretrained=False)
        num_ftrs = testmodel.fc.in_features
        testmodel.fc = nn.Linear(num_ftrs,2)
        testmodel.load_state_dict(torch.load(f'weights/{model}_{i}_L2/best.pth'))
        testmodel.cuda()

        for j in range(1,6):
            test_path = f'/media/data2/rjsdn/zoom/dataset/test{j}'
            test_img = datasets.ImageFolder(test_path,transform=transform)

            test_loader = DataLoader(test_img,batch_size=16,shuffle=False,num_workers=8)

            test_loss=0
            acc = 0
            count=0
            p,r=torch.tensor([]),torch.tensor([])
            testmodel.eval()
            with torch.no_grad():
                for x,y in tqdm(test_loader):
                    count+=1
                    x=x.cuda()
                    y=y.cuda()
                    output = testmodel(x)
                    pred=output.argmax(dim=1)
                    p=torch.cat([p,pred.to("cpu")])
                    r=torch.cat([r,y.to("cpu")])
                    acc += pred.eq(y.view_as(pred)).sum().item()
                acc /= len(test_img)
                print("ACC : %.5f"%(acc*100))

        print('#'*20)

R18 DFD


100%|██████████| 250/250 [00:04<00:00, 58.86it/s]


ACC : 45.40000


100%|██████████| 250/250 [00:04<00:00, 53.48it/s]


ACC : 48.75000


100%|██████████| 250/250 [00:04<00:00, 59.34it/s]


ACC : 49.37500


100%|██████████| 250/250 [00:04<00:00, 55.95it/s]


ACC : 49.15000


100%|██████████| 250/250 [00:03<00:00, 63.51it/s]


ACC : 46.65000
####################
R18 FS


100%|██████████| 250/250 [00:04<00:00, 58.28it/s]


ACC : 51.25000


100%|██████████| 250/250 [00:04<00:00, 53.77it/s]


ACC : 50.07500


100%|██████████| 250/250 [00:04<00:00, 58.90it/s]


ACC : 50.00000


100%|██████████| 250/250 [00:04<00:00, 56.28it/s]


ACC : 51.35000


100%|██████████| 250/250 [00:03<00:00, 63.07it/s]


ACC : 49.75000
####################
R18 DF


100%|██████████| 250/250 [00:04<00:00, 58.01it/s]


ACC : 48.45000


100%|██████████| 250/250 [00:04<00:00, 51.25it/s]


ACC : 48.17500


100%|██████████| 250/250 [00:04<00:00, 59.25it/s]


ACC : 47.27500


100%|██████████| 250/250 [00:04<00:00, 57.63it/s]


ACC : 44.30000


100%|██████████| 250/250 [00:03<00:00, 65.50it/s]


ACC : 44.82500
####################
R18 NS


100%|██████████| 250/250 [00:04<00:00, 57.19it/s]


ACC : 60.35000


100%|██████████| 250/250 [00:05<00:00, 48.48it/s]


ACC : 66.85000


100%|██████████| 250/250 [00:04<00:00, 59.11it/s]


ACC : 57.35000


100%|██████████| 250/250 [00:04<00:00, 57.44it/s]


ACC : 60.60000


100%|██████████| 250/250 [00:03<00:00, 66.52it/s]


ACC : 62.47500
####################
R18 F2F


100%|██████████| 250/250 [00:04<00:00, 55.21it/s]


ACC : 54.70000


100%|██████████| 250/250 [00:04<00:00, 53.74it/s]


ACC : 52.70000


100%|██████████| 250/250 [00:04<00:00, 60.99it/s]


ACC : 52.10000


100%|██████████| 250/250 [00:04<00:00, 57.34it/s]


ACC : 54.00000


100%|██████████| 250/250 [00:03<00:00, 65.55it/s]

ACC : 53.52500
####################


# compression

In [6]:
for model in m:
    for frame in f:
        for i in k:
            print(model,frame,i)
            testmodel=tmodels.xception(pretrained=False)
            if model == 'R18':
                testmodel = tmodels.resnet18(pretrained=False)
            num_ftrs = testmodel.fc.in_features
            testmodel.fc = nn.Linear(num_ftrs,2)
            testmodel.load_state_dict(torch.load(f'weights/{model}_t{frame}_{i}_low/best.pth'))
            testmodel.cuda()

            for j in range(1,6):
                test_path = f'/media/data2/rjsdn/zoom/dataset/compression/test{j}'
                test_img = datasets.ImageFolder(test_path,transform=transform)

                test_loader = DataLoader(test_img,batch_size=16,shuffle=False,num_workers=8)

                test_loss=0
                acc = 0
                count=0
                p,r=torch.tensor([]),torch.tensor([])
                testmodel.eval()
                with torch.no_grad():
                    for x,y in tqdm(test_loader):
                        count+=1
                        x=x.cuda()
                        y=y.cuda()
                        output = testmodel(x)
                        pred=output.argmax(dim=1)
                        p=torch.cat([p,pred.to("cpu")])
                        r=torch.cat([r,y.to("cpu")])
                        acc += pred.eq(y.view_as(pred)).sum().item()
                    acc /= len(test_img)
                    print("ACC : %.5f"%(acc*100))

            print('#'*20)

X 6 5


100%|██████████| 250/250 [00:24<00:00, 10.17it/s]


ACC : 98.35000


100%|██████████| 250/250 [00:20<00:00, 12.03it/s]


ACC : 99.30000


100%|██████████| 250/250 [00:24<00:00, 10.30it/s]


ACC : 96.47500


100%|██████████| 250/250 [00:19<00:00, 12.50it/s]


ACC : 97.57500


100%|██████████| 250/250 [00:17<00:00, 14.47it/s]


ACC : 98.05000
####################
X 6 10


100%|██████████| 250/250 [00:17<00:00, 14.63it/s]


ACC : 98.52500


100%|██████████| 250/250 [00:15<00:00, 16.19it/s]


ACC : 97.82500


100%|██████████| 250/250 [00:18<00:00, 13.60it/s]


ACC : 94.57500


100%|██████████| 250/250 [00:15<00:00, 15.99it/s]


ACC : 96.37500


100%|██████████| 250/250 [00:16<00:00, 15.27it/s]


ACC : 98.35000
####################
X 6 15


100%|██████████| 250/250 [00:16<00:00, 14.72it/s]


ACC : 97.50000


100%|██████████| 250/250 [00:15<00:00, 15.97it/s]


ACC : 98.02500


100%|██████████| 250/250 [00:16<00:00, 15.42it/s]


ACC : 95.57500


100%|██████████| 250/250 [00:13<00:00, 18.03it/s]


ACC : 95.50000


100%|██████████| 250/250 [00:13<00:00, 17.99it/s]

ACC : 97.70000
####################


#  NonCompression

In [4]:
for model in m:
    for frame in f:
        for i in k:
            print(model,frame,i)
            testmodel=tmodels.xception(pretrained=False)
            if model == 'R18':
                testmodel = tmodels.resnet18(pretrained=False)
            num_ftrs = testmodel.fc.in_features
            testmodel.fc = nn.Linear(num_ftrs,2)
            testmodel.load_state_dict(torch.load(f'weights/{model}_t{frame}_{i}_L2/best.pth'))
            testmodel.cuda()

            for j in range(1,8):
                test_path = f'/media/data2/rjsdn/zoom/dataset/test{j}'
                test_img = datasets.ImageFolder(test_path,transform=transform)

                test_loader = DataLoader(test_img,batch_size=16,shuffle=False,num_workers=8)

                test_loss=0
                acc = 0
                count=0
                p,r=torch.tensor([]),torch.tensor([])
                testmodel.eval()
                with torch.no_grad():
                    for x,y in tqdm(test_loader):
                        count+=1
                        x=x.cuda()
                        y=y.cuda()
                        output = testmodel(x)
                        pred=output.argmax(dim=1)
                        p=torch.cat([p,pred.to("cpu")])
                        r=torch.cat([r,y.to("cpu")])
                        acc += pred.eq(y.view_as(pred)).sum().item()
                    acc /= len(test_img)
                    print("ACC : %.5f"%(acc*100))

            print('#'*20)

X 7 5


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 56.10000


100%|██████████| 250/250 [00:07<00:00, 31.41it/s]


ACC : 58.67500


100%|██████████| 250/250 [00:07<00:00, 31.51it/s]


ACC : 55.95000


100%|██████████| 250/250 [00:08<00:00, 31.21it/s]


ACC : 55.77500


100%|██████████| 250/250 [00:07<00:00, 31.33it/s]


ACC : 54.62500


100%|██████████| 250/250 [00:07<00:00, 31.31it/s]


ACC : 97.39544


100%|██████████| 250/250 [00:07<00:00, 31.70it/s]


ACC : 95.62500
####################
X 7 10


100%|██████████| 250/250 [00:08<00:00, 31.02it/s]


ACC : 47.90000


100%|██████████| 250/250 [00:08<00:00, 31.05it/s]


ACC : 48.80000


100%|██████████| 250/250 [00:08<00:00, 31.01it/s]


ACC : 50.12500


100%|██████████| 250/250 [00:08<00:00, 30.75it/s]


ACC : 49.52500


100%|██████████| 250/250 [00:08<00:00, 31.18it/s]


ACC : 49.57500


100%|██████████| 250/250 [00:08<00:00, 31.09it/s]


ACC : 97.74606


100%|██████████| 250/250 [00:08<00:00, 30.94it/s]


ACC : 96.75000
####################
X 7 15


100%|██████████| 250/250 [00:08<00:00, 31.05it/s]


ACC : 54.80000


100%|██████████| 250/250 [00:07<00:00, 31.35it/s]


ACC : 62.17500


100%|██████████| 250/250 [00:07<00:00, 31.56it/s]


ACC : 64.80000


100%|██████████| 250/250 [00:08<00:00, 31.09it/s]


ACC : 63.50000


100%|██████████| 250/250 [00:08<00:00, 30.93it/s]


ACC : 57.72500


100%|██████████| 250/250 [00:07<00:00, 31.79it/s]


ACC : 96.79439


100%|██████████| 250/250 [00:08<00:00, 30.86it/s]

ACC : 96.30000
####################


In [25]:
# testmodel=tmodels.xception(pretrained=False)
testmodel=tmodels.resnet18(pretrained=False)
num_ftrs = testmodel.fc.in_features
testmodel.fc = nn.Linear(num_ftrs,2)
testmodel.load_state_dict(torch.load(f'weights/R18P_D//best.pth'))
testmodel.cuda()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act1): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act1): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act2): ReLU(inplace=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  

In [8]:
a = [1,1,0,0]
b = ['R18P_D','R18D_P','X_D','X_P_D']
for i in range(4):
    
    testmodel=tmodels.xception(pretrained=False)
    if a[i]==1: testmodel=tmodels.resnet18(pretrained=False)
    num_ftrs = testmodel.fc.in_features
    testmodel.fc = nn.Linear(num_ftrs,2)
    testmodel.load_state_dict(torch.load(f'weights/{b[i]}/best.pth'))
    testmodel.cuda()
    for j in range(1,6):
        test_path = f'/media/data2/rjsdn/zoom/dataset/test{j}'
        test_img = datasets.ImageFolder(test_path,transform=transform)

        test_loader = DataLoader(test_img,batch_size=16,shuffle=False,num_workers=8)

        test_loss=0
        acc = 0
        count=0
        p,r=torch.tensor([]),torch.tensor([])
        testmodel.eval()
        with torch.no_grad():
            for x,y in tqdm(test_loader):
                count+=1
                x=x.cuda()
                y=y.cuda()
                output = testmodel(x)
                pred=output.argmax(dim=1)
                pred = pred ^ 1
                p=torch.cat([p,pred.to("cpu")])
                r=torch.cat([r,y.to("cpu")])
                acc += pred.eq(y.view_as(pred)).sum().item()
            acc /= len(test_img)
            print("ACC : %.5f"%(acc*100))
#             report = classification_report(r,p,target_names=['fake','real'],digits=4)
            report = confusion_matrix(r,p)
            print(report)
            print('fake',report[:,0].sum(),'real',report[:,1].sum())
#             with open('report.txt','a') as f:
#                 f.write(report)



100%|██████████| 250/250 [00:03<00:00, 69.12it/s] 


ACC : 50.60000
[[1874  126]
 [1850  150]]
fake 3724 real 276


100%|██████████| 250/250 [00:04<00:00, 58.63it/s] 


ACC : 50.12500
[[1856  144]
 [1851  149]]
fake 3707 real 293


100%|██████████| 250/250 [00:03<00:00, 65.46it/s] 


ACC : 49.25000
[[1843  157]
 [1873  127]]
fake 3716 real 284


100%|██████████| 250/250 [00:04<00:00, 53.86it/s]


ACC : 47.77500
[[1814  186]
 [1903   97]]
fake 3717 real 283


100%|██████████| 250/250 [00:03<00:00, 70.47it/s] 


ACC : 47.62500
[[1787  213]
 [1882  118]]
fake 3669 real 331


100%|██████████| 250/250 [00:04<00:00, 61.96it/s]


ACC : 69.37500
[[1751  249]
 [ 976 1024]]
fake 2727 real 1273


100%|██████████| 250/250 [00:04<00:00, 57.76it/s] 


ACC : 68.95000
[[1702  298]
 [ 944 1056]]
fake 2646 real 1354


100%|██████████| 250/250 [00:03<00:00, 65.60it/s] 


ACC : 67.85000
[[1571  429]
 [ 857 1143]]
fake 2428 real 1572


100%|██████████| 250/250 [00:04<00:00, 57.82it/s] 


ACC : 72.82500
[[1636  364]
 [ 723 1277]]
fake 2359 real 1641


100%|██████████| 250/250 [00:03<00:00, 72.42it/s] 


ACC : 76.37500
[[1830  170]
 [ 775 1225]]
fake 2605 real 1395


100%|██████████| 250/250 [00:06<00:00, 37.47it/s]


ACC : 68.37500
[[1387  613]
 [ 652 1348]]
fake 2039 real 1961


100%|██████████| 250/250 [00:06<00:00, 36.32it/s]


ACC : 75.42500
[[1620  380]
 [ 603 1397]]
fake 2223 real 1777


100%|██████████| 250/250 [00:06<00:00, 35.89it/s]


ACC : 63.65000
[[1154  846]
 [ 608 1392]]
fake 1762 real 2238


100%|██████████| 250/250 [00:06<00:00, 36.02it/s]


ACC : 67.47500
[[1383  617]
 [ 684 1316]]
fake 2067 real 1933


100%|██████████| 250/250 [00:06<00:00, 36.67it/s]


ACC : 77.12500
[[1564  436]
 [ 479 1521]]
fake 2043 real 1957


100%|██████████| 250/250 [00:06<00:00, 36.90it/s]


ACC : 54.12500
[[1819  181]
 [1654  346]]
fake 3473 real 527


100%|██████████| 250/250 [00:07<00:00, 35.62it/s]


ACC : 54.35000
[[1816  184]
 [1642  358]]
fake 3458 real 542


100%|██████████| 250/250 [00:06<00:00, 36.36it/s]


ACC : 52.82500
[[1758  242]
 [1645  355]]
fake 3403 real 597


100%|██████████| 250/250 [00:06<00:00, 35.71it/s]


ACC : 50.82500
[[1784  216]
 [1751  249]]
fake 3535 real 465


100%|██████████| 250/250 [00:06<00:00, 35.80it/s]

ACC : 53.40000
[[1766  234]
 [1630  370]]
fake 3396 real 604
